package model;
// Generated 21 Feb 2016 9:49:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdministratorId generated by hbm2java
 */
@Embeddable
public class AdministratorId  implements java.io.Serializable {


     private String adminName;
     private int accountAccountId;

    public AdministratorId() {
    }

    public AdministratorId(String adminName, int accountAccountId) {
       this.adminName = adminName;
       this.accountAccountId = accountAccountId;
    }
   


    @Column(name="admin_name", unique=true, nullable=false, length=200)
    public String getAdminName() {
        return this.adminName;
    }
    
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }


    @Column(name="account_account_id", unique=true, nullable=false)
    public int getAccountAccountId() {
        return this.accountAccountId;
    }
    
    public void setAccountAccountId(int accountAccountId) {
        this.accountAccountId = accountAccountId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdministratorId) ) return false;
		 AdministratorId castOther = ( AdministratorId ) other; 
         
		 return ( (this.getAdminName()==castOther.getAdminName()) || ( this.getAdminName()!=null && castOther.getAdminName()!=null && this.getAdminName().equals(castOther.getAdminName()) ) )
 && (this.getAccountAccountId()==castOther.getAccountAccountId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAdminName() == null ? 0 : this.getAdminName().hashCode() );
         result = 37 * result + this.getAccountAccountId();
         return result;
   }   


}


