package model;
// Generated 21 Feb 2016 9:49:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name="car"
    ,catalog="clienteledbsystem"
    , uniqueConstraints = {@UniqueConstraint(columnNames="policy_id"), @UniqueConstraint(columnNames="carcol"), @UniqueConstraint(columnNames="insurance_insurance_id")} 
)
public class Car  implements java.io.Serializable {


     private CarId id;
     private Insurance insurance;
     private String carType;
     private Date yearModel;
     private Double monthlyPay;
     private String carcol;

    public Car() {
    }

	
    public Car(CarId id, Insurance insurance) {
        this.id = id;
        this.insurance = insurance;
    }
    public Car(CarId id, Insurance insurance, String carType, Date yearModel, Double monthlyPay, String carcol) {
       this.id = id;
       this.insurance = insurance;
       this.carType = carType;
       this.yearModel = yearModel;
       this.monthlyPay = monthlyPay;
       this.carcol = carcol;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="policyId", column=@Column(name="policy_id", unique=true, nullable=false) ), 
        @AttributeOverride(name="insuranceInsuranceId", column=@Column(name="insurance_insurance_id", unique=true, nullable=false) ) } )
    public CarId getId() {
        return this.id;
    }
    
    public void setId(CarId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="insurance_insurance_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Insurance getInsurance() {
        return this.insurance;
    }
    
    public void setInsurance(Insurance insurance) {
        this.insurance = insurance;
    }

    
    @Column(name="car_type", length=100)
    public String getCarType() {
        return this.carType;
    }
    
    public void setCarType(String carType) {
        this.carType = carType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="year_model", length=0)
    public Date getYearModel() {
        return this.yearModel;
    }
    
    public void setYearModel(Date yearModel) {
        this.yearModel = yearModel;
    }

    
    @Column(name="monthly_pay", precision=22, scale=0)
    public Double getMonthlyPay() {
        return this.monthlyPay;
    }
    
    public void setMonthlyPay(Double monthlyPay) {
        this.monthlyPay = monthlyPay;
    }

    
    @Column(name="carcol", unique=true, length=45)
    public String getCarcol() {
        return this.carcol;
    }
    
    public void setCarcol(String carcol) {
        this.carcol = carcol;
    }




}


