package model;
// Generated 21 Feb 2016 9:49:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarId generated by hbm2java
 */
@Embeddable
public class CarId  implements java.io.Serializable {


     private int policyId;
     private int insuranceInsuranceId;

    public CarId() {
    }

    public CarId(int policyId, int insuranceInsuranceId) {
       this.policyId = policyId;
       this.insuranceInsuranceId = insuranceInsuranceId;
    }
   


    @Column(name="policy_id", unique=true, nullable=false)
    public int getPolicyId() {
        return this.policyId;
    }
    
    public void setPolicyId(int policyId) {
        this.policyId = policyId;
    }


    @Column(name="insurance_insurance_id", unique=true, nullable=false)
    public int getInsuranceInsuranceId() {
        return this.insuranceInsuranceId;
    }
    
    public void setInsuranceInsuranceId(int insuranceInsuranceId) {
        this.insuranceInsuranceId = insuranceInsuranceId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CarId) ) return false;
		 CarId castOther = ( CarId ) other; 
         
		 return (this.getPolicyId()==castOther.getPolicyId())
 && (this.getInsuranceInsuranceId()==castOther.getInsuranceInsuranceId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPolicyId();
         result = 37 * result + this.getInsuranceInsuranceId();
         return result;
   }   


}


