package model;
// Generated 21 Feb 2016 9:49:20 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="clienteledbsystem"
    , uniqueConstraints = {@UniqueConstraint(columnNames="client_id"), @UniqueConstraint(columnNames="occupation_job_id"), @UniqueConstraint(columnNames="account_account_id"), @UniqueConstraint(columnNames="insurance_insurance_id")} 
)
public class Client  implements java.io.Serializable {


     private ClientId id;
     private Account account;
     private Insurance insurance;
     private Occupation occupation;
     private String firstName;
     private String middleName;
     private String lastName;
     private String address;
     private String gender;
     private String maritalStatus;
     private Integer cellNumber;

    public Client() {
    }

	
    public Client(ClientId id, Account account, Insurance insurance, Occupation occupation) {
        this.id = id;
        this.account = account;
        this.insurance = insurance;
        this.occupation = occupation;
    }
    public Client(ClientId id, Account account, Insurance insurance, Occupation occupation, String firstName, String middleName, String lastName, String address, String gender, String maritalStatus, Integer cellNumber) {
       this.id = id;
       this.account = account;
       this.insurance = insurance;
       this.occupation = occupation;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.address = address;
       this.gender = gender;
       this.maritalStatus = maritalStatus;
       this.cellNumber = cellNumber;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="clientId", column=@Column(name="client_id", unique=true, nullable=false) ), 
        @AttributeOverride(name="occupationJobId", column=@Column(name="occupation_job_id", unique=true, nullable=false) ), 
        @AttributeOverride(name="accountAccountId", column=@Column(name="account_account_id", unique=true, nullable=false) ), 
        @AttributeOverride(name="insuranceInsuranceId", column=@Column(name="insurance_insurance_id", unique=true, nullable=false) ) } )
    public ClientId getId() {
        return this.id;
    }
    
    public void setId(ClientId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account_account_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="insurance_insurance_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Insurance getInsurance() {
        return this.insurance;
    }
    
    public void setInsurance(Insurance insurance) {
        this.insurance = insurance;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="occupation_job_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Occupation getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(Occupation occupation) {
        this.occupation = occupation;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="middle_name", length=45)
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="address", length=200)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="gender", length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="marital_status", length=10)
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    
    @Column(name="cell_number")
    public Integer getCellNumber() {
        return this.cellNumber;
    }
    
    public void setCellNumber(Integer cellNumber) {
        this.cellNumber = cellNumber;
    }




}


