package model;
// Generated 21 Feb 2016 9:49:20 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Individual generated by hbm2java
 */
@Entity
@Table(name="individual"
    ,catalog="clienteledbsystem"
    , uniqueConstraints = {@UniqueConstraint(columnNames="identity_number"), @UniqueConstraint(columnNames="insurance_insurance_id")} 
)
public class Individual  implements java.io.Serializable {


     private IndividualId id;
     private Insurance insurance;
     private String coverType;
     private Double monthlyPay;

    public Individual() {
    }

	
    public Individual(IndividualId id, Insurance insurance) {
        this.id = id;
        this.insurance = insurance;
    }
    public Individual(IndividualId id, Insurance insurance, String coverType, Double monthlyPay) {
       this.id = id;
       this.insurance = insurance;
       this.coverType = coverType;
       this.monthlyPay = monthlyPay;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="identityNumber", column=@Column(name="identity_number", unique=true, nullable=false, length=13) ), 
        @AttributeOverride(name="insuranceInsuranceId", column=@Column(name="insurance_insurance_id", unique=true, nullable=false) ) } )
    public IndividualId getId() {
        return this.id;
    }
    
    public void setId(IndividualId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="insurance_insurance_id", unique=true, nullable=false, insertable=false, updatable=false)
    public Insurance getInsurance() {
        return this.insurance;
    }
    
    public void setInsurance(Insurance insurance) {
        this.insurance = insurance;
    }

    
    @Column(name="cover_type", length=100)
    public String getCoverType() {
        return this.coverType;
    }
    
    public void setCoverType(String coverType) {
        this.coverType = coverType;
    }

    
    @Column(name="monthly_pay", precision=22, scale=0)
    public Double getMonthlyPay() {
        return this.monthlyPay;
    }
    
    public void setMonthlyPay(Double monthlyPay) {
        this.monthlyPay = monthlyPay;
    }




}


