package model;
// Generated 21 Feb 2016 9:49:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Insurance generated by hbm2java
 */
@Entity
@Table(name="insurance"
    ,catalog="clienteledbsystem"
)
public class Insurance  implements java.io.Serializable {


     private int insuranceId;
     private String insuranceType;
     private Set<Client> clients = new HashSet<Client>(0);
     private Set<Individual> individuals = new HashSet<Individual>(0);
     private Set<Member> members = new HashSet<Member>(0);
     private Set<Car> cars = new HashSet<Car>(0);

    public Insurance() {
    }

	
    public Insurance(int insuranceId) {
        this.insuranceId = insuranceId;
    }
    public Insurance(int insuranceId, String insuranceType, Set<Client> clients, Set<Individual> individuals, Set<Member> members, Set<Car> cars) {
       this.insuranceId = insuranceId;
       this.insuranceType = insuranceType;
       this.clients = clients;
       this.individuals = individuals;
       this.members = members;
       this.cars = cars;
    }
   
     @Id 

    
    @Column(name="insurance_id", unique=true, nullable=false)
    public int getInsuranceId() {
        return this.insuranceId;
    }
    
    public void setInsuranceId(int insuranceId) {
        this.insuranceId = insuranceId;
    }

    
    @Column(name="insurance_type", length=45)
    public String getInsuranceType() {
        return this.insuranceType;
    }
    
    public void setInsuranceType(String insuranceType) {
        this.insuranceType = insuranceType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insurance")
    public Set<Client> getClients() {
        return this.clients;
    }
    
    public void setClients(Set<Client> clients) {
        this.clients = clients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insurance")
    public Set<Individual> getIndividuals() {
        return this.individuals;
    }
    
    public void setIndividuals(Set<Individual> individuals) {
        this.individuals = individuals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insurance")
    public Set<Member> getMembers() {
        return this.members;
    }
    
    public void setMembers(Set<Member> members) {
        this.members = members;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insurance")
    public Set<Car> getCars() {
        return this.cars;
    }
    
    public void setCars(Set<Car> cars) {
        this.cars = cars;
    }




}


