package model;
// Generated 21 Feb 2016 9:49:20 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId  implements java.io.Serializable {


     private String userName;
     private int accountAccountId;

    public UserId() {
    }

    public UserId(String userName, int accountAccountId) {
       this.userName = userName;
       this.accountAccountId = accountAccountId;
    }
   


    @Column(name="user_name", unique=true, nullable=false, length=200)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


    @Column(name="account_account_id", unique=true, nullable=false)
    public int getAccountAccountId() {
        return this.accountAccountId;
    }
    
    public void setAccountAccountId(int accountAccountId) {
        this.accountAccountId = accountAccountId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserId) ) return false;
		 UserId castOther = ( UserId ) other; 
         
		 return ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) )
 && (this.getAccountAccountId()==castOther.getAccountAccountId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         result = 37 * result + this.getAccountAccountId();
         return result;
   }   


}


